### ISSUE TITLE
Doesnt Run on Mac OS Catalina

### ISSUE THREAD

**Issue by d3rpp** [memetrooper/TEXTREME#24]
Error: 
'The application “TEXTREME” can’t be opened.'
I apologize for I am unable to provide any more details

**Comment by saulbensach** [comment]
The executable inside the app folder needs execution permissions
Fix:
`chmod +x TEXTREME.app/Contents/MacOS/TEXTREME`

Then open the app normally

**Comment by lucaslsf** [comment]
@saulbensach I have tried that but it still doesn't work somehow — I used right-click open in `TEXTREME.app/Contents/MacOS/TEXTREME`, said it's ok to open and still get the same error 🤔

**Comment by saulbensach** [comment]
@lucaslsf The chmod +x think worked for me I'm using macOS Catalina 10.15.3, the thing is that you give +x permissions to Contents/MacOS/TEXTREME and then you open Textreme.app normally.
This worked for me, maybe opening it with `open` command brings some clue.

**Comment by lucaslsf** [comment]
I'm a bit out of my dept here now, sorry.
Do you just go Terminal and `chmod +x TEXTREME.app/Contents/MacOS/TEXTREME` ?

**Comment by saulbensach** [comment]
@lucaslsf yes

**Comment by lucaslsf** [comment]
Managed to make it work — just had to move the app and navigate to the `/Applications` folder in the terminal before using that command :)

Thanks @saulbensach

**Comment by vetras** [comment]
I was thinking about creating an issue but maybe I'll just ask first.
Can I `brew install` this ?
If not, what would be required to do so?

**Comment by eXCoreX** [comment]
> I was thinking about creating an issue but maybe I'll just ask first.
> Can I `brew install` this ?
> If not, what would be required to do so?

You can't because there's no textreme formula.
