### ISSUE TITLE
Trying to assign value of type 'HboxContainer' to a variable of type 'LineEdit'

### ISSUE THREAD

**Issue by sutble** [memetrooper/TEXTREME#29]
Im running macos mojave, and Im seeing this error 
<img width="910" alt="Screen Shot 2021-01-25 at 7 42 46 PM" src="https://user-images.githubusercontent.com/10662653/105805251-b2ad0e00-5f45-11eb-9947-185312090ead.png">

If I change stock_bar_path to be a LineEdit (such as $SpacialLineEdit2) then it runs normally

**Comment by maksloboda** [comment]
Fixed by af9f07adde3aa621b63c00365cfdfbad088bbf8b
