### ISSUE TITLE
Better Syntax

### ISSUE THREAD

**Issue by WilliamRagstad** [memetrooper/TEXTREME#4]
You should make it possible to create syntax bound to a specific file extension! And if you add that, you should be able to choose (when creating a new file) what file type it is going to be before saving it and loading the correct syntax for it.
Starting with "plain text", and if you click on it (for example), you can select from a list of existing syntax:es like: html, css, JavaScript, C#, Java, Ruby, Lua, and so on, you get the point. These syntax:es would be cool if they came pre-installed in a folder.
* ./root
     * /syntax
          * /html.txt
          * /css.txt
          * /javascript.txt
          * /my custom syntax.txt

**Comment by benjhar** [comment]
This issue is now fixed and needs closing.
