### ISSUE TITLE
add rgb support

### ISSUE THREAD

**Issue by benjhar** [memetrooper/TEXTREME#7]
add hex colours support in the syntax.txt file. This makes it easier to pick colours, instead of rooting through the colours you have in the How to add syntax.txt file. For example, in python, the syntax.txt file would read:
`import,#ba5bff`
You could also allow for rgb, cmyk if hex is not as easy.

edit:
having looked into it, I discovered that you could instead use Color8 instead of ColorN and people could use rgb codes

**Comment by thenamesweretakenalready** [comment]
having looked into it, I discovered that you could instead use Color8 instead of ColorN and people could use rgb codes
