### ISSUE TITLE
Godot project doesn't run

### ISSUE THREAD

**Issue by nezvers** [memetrooper/TEXTREME#8]
![Capture](https://user-images.githubusercontent.com/26794315/59161310-d5c54880-8ae9-11e9-8b94-02b2ee7b7453.PNG)
Windows 10, i7-6700k, GTX1060, 16GB RAM.
EXE from itch.io works.
I'm new to Godot and wanted to learn from the project.

**Comment by Fox-Islam** [comment]
I'm having this same issue, running on Linux 64-bit (Ubuntu 18.04). The only thing I could think of that's causing this is running the project in a newer version of Godot (v3.1.1) than it was written in and it introducing some breaking changes.

**Comment by mrnotcrazy** [comment]
If you comment out loadsyntax() in base.gd it will load. Probably a linux issue as I am also running ubuntu. If I have time I will try to trouble shoot it more when I get home.

**Comment by Fox-Islam** [comment]
Ah! Thank you, doing that helped me debug the issue properly, will open a PR as soon as I can (Update: https://github.com/memetrooper/TEXTREME/pull/12)
