### ISSUE TITLE
No juice when deleting a selection

### ISSUE THREAD

**Issue by Pigmassacre** [memetrooper/TEXTREME#9]
![textreme_selection_deletion](https://user-images.githubusercontent.com/3669856/59204752-9823f680-8ba1-11e9-95f4-309fa06cd315.gif)

**Comment by MrAlexEsisteGia** [comment]
+1

**Comment by Papayaman1000** [comment]
Doesn't seem to have *quite* so fabulous of explosions with CTRL+Backspace, either.

![ctrlback](https://user-images.githubusercontent.com/24946071/59282642-3dd57500-8c37-11e9-9d5e-647cce902347.gif)

**Comment by cis-ash** [comment]
Fixed in Textreme 2.0
